export default {
  "login": "SamarthaKhare",
  "id": 97874411,
  "node_id": "U_kgDOBdVx6w",
  "avatar_url": "https://avatars.githubusercontent.com/u/97874411?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/SamarthaKhare",
  "html_url": "https://github.com/SamarthaKhare",
  "followers_url": "https://api.github.com/users/SamarthaKhare/followers",
  "following_url": "https://api.github.com/users/SamarthaKhare/following{/other_user}",
  "gists_url": "https://api.github.com/users/SamarthaKhare/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/SamarthaKhare/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/SamarthaKhare/subscriptions",
  "organizations_url": "https://api.github.com/users/SamarthaKhare/orgs",
  "repos_url": "https://api.github.com/users/SamarthaKhare/repos",
  "events_url": "https://api.github.com/users/SamarthaKhare/events{/privacy}",
  "received_events_url": "https://api.github.com/users/SamarthaKhare/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Samartha Khare",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Web Developer | Back-end specialist with UX design background | Proficient in React.js | Express | NodeJs| Passionate about creating clean, responsive websites",
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 26,
  "created_at": "2022-01-17T07:33:14Z",
  "updated_at": "2023-06-28T11:56:09Z"
};
